# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171219_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnahtarKelimeSaydirma',
        ),
    ]
